--final modifications of prototypes go here
--filling in reactions to other modded prototypes, stack sizes, graphical tweaks, etc
--a prototype can be data:extend'ed here but... don't expect it to work well with other mods