data:extend({
    {
    type = "item",
    name = "dogecoin-mining-rig",
    icon = don_entities_icons_path .. "dogecoin-mining-rig.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[dogecoin-mining-rig]",
    place_result = "dogecoin-mining-rig",
    stack_size = 50,
  },
  {
    type = "item",
    name = "dogecoin-mining-farm",
    icon = don_entities_icons_path .. "dogecoin-mining-farm.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[dogecoin-mining-farm]",
    place_result = "dogecoin-mining-farm",
    stack_size = 50,
  },
  {
    type = "item",
    name = "dogecoin-mining-supercomputer",
    icon = don_entities_icons_path .. "dogecoin-mining-supercomputer.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[dogecoin-mining-supercomputer]",
    place_result = "dogecoin-mining-supercomputer",
    stack_size = 50,
  },
})
