data:extend({
    {
    type = "item",
    name = "dogecoin-mining-rig",
    icon = don_entities_icons_path .. "dogecoin-mining-rig.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[dogecoin-mining]-d1[dogecoin-mining-rig]",
    place_result = "dogecoin-mining-rig",
    stack_size = 50,
  },
  {
    type = "item",
    name = "dogecoin-mining-farm",
    icon = don_entities_icons_path .. "dogecoin-mining-farm.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[dogecoin-mining]-d2[dogecoin-mining-farm]",
    place_result = "dogecoin-mining-farm",
    stack_size = 50,
  },
  {
    type = "item",
    name = "dogecoin-mining-supercomputer",
    icon = don_entities_icons_path .. "dogecoin-mining-supercomputer.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[dogecoin-mining]-d3[dogecoin-mining-supercomputer]",
    place_result = "dogecoin-mining-supercomputer",
    stack_size = 50,
  },
  {
    type = "item",
    name = "designated-orbital-grounding-entity",
    icon = don_entities_icons_path .. "designated-orbital-grounding-entity.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[dogecoin-mining]-d4[designated-orbital-grounding-entity]",
    place_result = "designated-orbital-grounding-entity",
    stack_size = 50,
  },
  {
    type = "item",
    name = "dogerium-conductor",
    icon = don_entities_icons_path .. "dogerium-conductor.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "energy-pipe-distribution",
    order = "a[pipes]-a2[dogerium-conductor]",
    place_result = "dogerium-conductor",
    stack_size = 100,
  },
  {
    type = "item",
    name = "dogerium-transmitter",
    icon = don_entities_icons_path .. "dogerium-transmitter.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "energy-pipe-distribution",
    order = "a[pipes]-b2[dogerium-transmitter]",
    place_result = "dogerium-transmitter",
    stack_size = 50,
  },
  {
    type = "item",
    name = "dogerium-wallet",
    icon = don_entities_icons_path .. "dogerium-wallet.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "storage",
    order = "b[fluid]-c[dogerium-wallet]",
    place_result = "dogerium-wallet",
    stack_size = 50,
  },
})
